### ISSUE TITLE
Error in the maximum length of the otherReasonInfo

### ISSUE THREAD

**Issue by porosnie** [eurocontrol-swim/geofencing-deploy#3]
The JSON Schema copy contained in ED-269, Appendix 2, has an editorial error. On page 55, the maximum length of the otherReasonInfo element is declared as "30". This is not according to the data model contained in ED-269, Chapter 8, where the data type of the otherReasonInfo element is TextShortType, with a maximum length of 200 characters. The correct declaration of this element is:

    "otherReasonInfo": {
      "type": "string",
      "maxLength": 200
    },

**Comment by fjcrabiffosse** [comment]
#4 Fixed.
